# 数据库连接参数

spring:
  datasource:
    url: jdbc:mysql://139.224.55.152:3306/atcrowdfunding
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
# 应用名称
  application:
    name: scw-order
# 配置redis的连接地址+端口号+密码
  redis:
    host: 139.224.55.152
    port: 16379
# mybatis配置
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
  
# 端口号
server:
  port: 9000
# 注册到的注册中心的地址  
eureka:
  client:
    service-url:
       defaultZone: http://101.132.138.187:8761/eureka/
  instance:
    prefer-ip-address: true  # 支持注册中心使用当前应用的ip地址
    ip-address: 101.133.235.233     # 指定当前应用的ip地址
    
